# Generated by Django 3.2.2 on 2021-05-10 10:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('user_name', models.CharField(max_length=150, unique=True)),
                ('nick_name', models.CharField(blank=True, max_length=150)),
                ('profile_image', models.ImageField(blank=True, height_field=200, null=True, upload_to='images/', verbose_name='user image', width_field=200)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='phone number')),
                ('about', models.TextField(blank=True, max_length=500, verbose_name='about')),
                ('joined_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
